// Auto-match maps: CSV/JSON header → DB field name
// Used by the frontend to auto-suggest field mapping before import.
// Keys cover both Bubble API key format AND Bubble display name format.

export const IMPORT_FIELD_MAPS = {
  Staff: {
    "_id": "bubble_id",
    "al_quota_number": "al_quota", "AL Quota": "al_quota",
    "birthday_date": "birthday", "Birthday": "birthday",
    "brands_list_text": "brands", "Brands": "brands",
    "business_email_text": "business_email", "Business Email": "business_email",
    "clock_in_face_image": "clock_in_face",
    "clock_in_face_amazon_id_text": "clock_in_face_amazon_id",
    "clock_in_face_amazon_id_2_text": "clock_in_face_amazon_id_2",
    "dingding_dept_id_text": "dingding_dept_id", "DingDing Dept Id": "dingding_dept_id",
    "dingding_user_id_text": "dingding_user_id", "DingDing User Id": "dingding_user_id",
    "direct_phone_text": "direct_phone", "Direct Phone": "direct_phone",
    "display_text": "display_name", "Display Name": "display_name",
    "entry_date_date": "entry_date", "Entry Date": "entry_date",
    "full_name_text": "full_name", "Full Name": "full_name",
    "hotline_text": "hotline", "Hotline": "hotline",
    "new_direct_phone_text": "new_direct_phone",
    "new_work_phone_text": "new_work_phone",
    "no_clockin_boolean": "no_clockin",
    "no_man_hour_task_boolean": "no_man_hour_task",
    "position_text": "position", "Position": "position",
    "private_email_text": "private_email", "Private Email": "private_email",
    "private_phone_text": "private_phone", "Private Phone": "private_phone",
    "profile_pic_image": "profile_pic", "Profile Pic": "profile_pic",
    "termination_date_date": "termination_date", "Termination Date": "termination_date",
    "voov_id_text": "voov_id", "Voov ID": "voov_id",
    "work_email_text": "work_email", "Work Email": "work_email",
    "work_phone_text": "work_phone", "Work Phone": "work_phone",
    "o_base_location_option_o_base_location": "base_location", "O_Base Location": "base_location",
    "o_probation_option_o_probation": "o_probation", "O_Probation": "o_probation",
    "o_status_option_o_staff_status": "o_status", "O_Status": "o_status",
    "o_status_text_text": "o_status_text",
    "o_user_role_option_os_user_role": "o_user_role", "O_User Role": "o_user_role",
    "n_bu_custom_nos_bu": "n_bu", "N_BU": "n_bu",
    "n_team_custom_nos_team": "n_team", "N_Team": "n_team",
    "n_team_role_custom_nos_team_role": "n_team_role", "N_Team Role": "n_team_role",
    "team_leader_custom_staff": "team_leader", "Team Leader": "team_leader",
    "chinese_name_text": "chinese_name", "Chinese Name": "chinese_name",
  },
  BubbleOT: {
    "_id": "bubble_id",
    "remarks_text": "remarks", "Remarks": "remarks",
    "ot_hour_number": "ot_hour", "OT Hour": "ot_hour",
    "event_name_text": "event_name", "Event Name": "event_name",
    "reject_reason_text": "reject_reason", "Reject Reason": "reject_reason",
    "staff_custom_staff": "staff_id", "Staff": "staff_id",
    "end_date__time_date": "end_date_time", "End Date& Time": "end_date_time",
    "is_interview_boolean": "is_interview", "Is Interview": "is_interview",
    "start_date__time_date": "start_date_time", "Start Date& Time": "start_date_time",
    "r_clcok_in_custom_clockin": "clockin_id", "R_Clcok-in": "clockin_id",
    "n_ot_type_custom_nos_ot_type": "ot_type", "N_OT Type": "ot_type",
    "status_option_os_approval_status": "status", "Status": "status",
  },
  BubbleLeave: {
    "_id": "bubble_id",
    "prove_image": "prove_url", "Prove": "prove_url",
    "remarks_text": "remarks", "Remarks": "remarks",
    "_quota_number": "quota", "-Quota": "quota",
    "count_year_date": "count_year", "Count Year": "count_year",
    "info_tech_image": "info_tech_url", "Info-Tech": "info_tech_url",
    "approved_boolean": "approved", "Approved": "approved",
    "display_text": "display_name", "Display Name": "display_name",
    "reject_reason_text": "reject_reason", "Reject Reason": "reject_reason",
    "send_email_boolean": "send_email", "Send Email": "send_email",
    "staff_custom_staff": "staff_id", "Staff": "staff_id",
    "end_date___time_date": "end_date_time", "End Date & Time": "end_date_time",
    "google_event_id_text": "google_event_id", "Google Event ID": "google_event_id",
    "approver_custom_staff": "approver_id", "Approver": "approver_id",
    "rejecter_custom_staff": "rejecter_id", "Rejecter": "rejecter_id",
    "start_date___time_date": "start_date_time", "Start Date & Time": "start_date_time",
    "application_reason_text": "application_reason", "Application Reason": "application_reason", "Reason for Apply": "application_reason",
    "interview_email_boolean": "interview_email", "Interview Email": "interview_email",
    "send_approval_email_boolean": "send_approval_email", "Send Approval Email": "send_approval_email",
    "n_leave_type_custom_nos_leave_type": "leave_type", "N_Leave Type": "leave_type",
    "n_leave_period_option_os_leave_period": "leave_period", "N_Leave Period": "leave_period",
  },
  BubbleClockin: {
    "_id": "bubble_id",
    "prove___out_image": "prove_out_url", "Prove - Out": "prove_out_url",
    "remarks_text": "remarks_in", "Remarks": "remarks_in", "Remarks - In": "remarks_in",
    "face_image___in_image": "face_image_in_url", "Face Image - In": "face_image_in_url",
    "prove___in_image": "prove_in_url", "Prove - In": "prove_in_url",
    "clock_in_time_date": "clockin_time", "Clock In Time": "clockin_time",
    "ot_minutes_approved_number": "ot_minutes", "OT Minutes Approved": "ot_minutes",
    "remarks___out_text": "remarks_out", "Remarks - Out": "remarks_out",
    "staff_custom_staff": "staff_id", "Staff": "staff_id",
    "clock_out_time_date": "clock_out_time", "Clock Out Time": "clock_out_time",
    "late_minutes_number": "late_minutes", "Late Minutes": "late_minutes",
    "accuracy___in_number": "accuracy_in", "Accuracy - In": "accuracy_in",
    "accuracy___out_number": "accuracy_out", "Accuracy - Out": "accuracy_out",
    "face_image___out_image": "face_image_out_url", "Face Image - Out": "face_image_out_url",
    "face_image_file_url___in_text": "face_image_file_url_in", "Face Image File URL - In": "face_image_file_url_in", "Face Image File Url - In": "face_image_file_url_in",
    "reason_for_no_clock_text": "reason_for_no_clock", "Reason for No Clock": "reason_for_no_clock", "Reason For No Clock": "reason_for_no_clock",
    "request_update_end_time_date": "request_update_end_time", "Request Update End Time": "request_update_end_time",
    "face_image_file_url___out_text": "face_image_file_url_out", "Face Image File URL - Out": "face_image_file_url_out", "Face Image File Url - Out": "face_image_file_url_out",
    "request_update_start_time_date": "request_update_start_time", "Request Update Start Time": "request_update_start_time",
    "geo_location___in_geographic_address": "geo_location_in", "Geo Location - In": "geo_location_in",
    "geo_location___out_geographic_address": "geo_location_out", "Geo Location - Out": "geo_location_out",
    "google_location___in_text": "google_location_in", "Google Location - In": "google_location_in",
    "google_location___out_text": "google_location_out", "Google Location - Out": "google_location_out",
    "o_status___in_option_o_clockin_status": "status_in", "O_Status - In": "status_in",
    "o_status___out_option_o_clockin_status": "status_out", "O_Status - Out": "status_out",
    "tag___in_list_text": "tags_in", "Tags - in": "tags_in", "Tag - In": "tags_in",
    "tag___out_list_text": "tags_out", "Tags - out": "tags_out", "Tag - Out": "tags_out",
    "n_work_location_custom_nos_work_location": "work_location_in", "N_Work Location": "work_location_in", "N_Work Location - In": "work_location_in",
    "n_work_location___out_custom_nos_work_location": "work_location_out", "N_Work Location - Out": "work_location_out",
    "o_photo_approval___in_option_o_photo_approval": "photo_approval_in", "O_Photo Approval - In": "photo_approval_in",
    "o_photo_approval___out_option_o_photo_approval": "photo_approval_out", "O_Photo Approval - Out": "photo_approval_out",
    "request_update_end_location_text": "request_update_end_location", "Request Update End Location": "request_update_end_location",
    "request_update_start_location_text": "request_update_start_location", "Request Update Start Location": "request_update_start_location",
    "ding_ding_in_attendance_id_text": "dingding_in_attendance_id", "Ding Ding In Attendance Id": "dingding_in_attendance_id", "DingDing In Attendance Id": "dingding_in_attendance_id",
    "ding_ding_out_attendance_id_text": "dingding_out_attendance_id", "Ding Ding Out Attendance Id": "dingding_out_attendance_id", "DingDing Out Attendance Id": "dingding_out_attendance_id",
  },
  BubbleManHourDate: {
    "_id": "bubble_id",
    "report_date_date": "report_date", "Report Date": "report_date",
    "staff_custom_staff": "staff_id", "Staff": "staff_id",
    "total_work_hour_number": "total_work_hour", "Total Work Hour": "total_work_hour",
  },
  BubbleManHourTask: {
    "_id": "bubble_id",
    "asana_link_text": "asana_link", "Asana Link": "asana_link",
    "work_hour_number": "work_hour", "Work Hour": "work_hour",
    "images_list_image": "images", "Images": "images",
    "keywords_text": "keywords", "Keywords": "keywords",
    "meeting_topic_text": "meeting_topic", "Meeting Topic": "meeting_topic",
    "output_count_number": "output_count", "Output Count": "output_count",
    "task_description_text": "task_description", "Task Description": "task_description",
    "n_task_custom_nos_task": "task_id", "N_Task": "task_id",
    "project_custom_project": "project_id", "Project": "project_id",
    "n_brand_custom_nos_brand": "brand_id", "N_Brand": "brand_id",
    "meeting_invite_sent_boolean": "meeting_invite_sent",
    "projects_list_custom_project": "projects", "Projects": "projects",
    "n_task_type_custom_nos_task_type": "task_type_id", "N_Task Type": "task_type_id",
    "man_hour_date_custom_man_hour_date": "man_hour_date_id", "Man Hour Date": "man_hour_date_id",
    "meeting_participant_list_custom_staff": "meeting_participants", "Meeting Participant": "meeting_participants",
    "o_meeting_method_option_os_meeting_method": "meeting_method", "O_Meeting Method": "meeting_method",
    "n_output___unit_custom_nos_output___unit": "output_unit", "N_Output & Unit": "output_unit",
    "n_work_location_custom_nos_work_location": "work_location", "N_Work Location": "work_location",
    "o_meeting_duration_option_os_meeting_duration": "meeting_duration", "O_Meeting Duration": "meeting_duration",
    "o_meeting_request_date_option_o_meeting_request_date": "meeting_request_date", "O_Meeting Request Date": "meeting_request_date",
  },
  BubbleProject: {
    "_id": "bubble_id",
    "outcome_text": "outcome", "Outcome": "outcome",
    "asana_link_text": "asana_link", "Asana Link": "asana_link",
    "pic_custom_staff": "pic_id", "PIC": "pic_id",
    "display_text": "display_name", "Display Name": "display_name",
    "start_date_date": "started_date", "Start Date": "started_date",
    "bubble_api_id_text": "bubble_api_id", "Bubble API ID": "bubble_api_id",
    "is_key_project_boolean": "is_key_project", "Is Key Project": "is_key_project",
    "estimated_income_number": "estimated_income", "Estimated Income": "estimated_income",
    "estimated_expense_number": "estimated_expense", "Estimated Expense": "estimated_expense",
    "estimated_man_hour_number": "estimated_man_hour", "Estimated Man Hour": "estimated_man_hour",
    "n_brands_list_custom_nos_brand": "brands", "N_Brands": "brands",
    "collaborator_list_custom_staff": "collaborators", "Collaborator": "collaborators",
    "o_status_option_os_project_status": "status", "O_Status": "status",
    "n_teams_list_custom_nos_team": "teams", "N_Teams": "teams",
    "o_location_list_option_o_base_location": "locations", "O_Location": "locations",
    "limited_to_role_list_custom_nos_team_role": "roles", "Limited to Role": "roles",
    "sub_projects_list_custom_project": "sub_projects", "Sub-Projects": "sub_projects",
    "n_task_types_list_custom_nos_task_type": "task_types", "N_Task Types": "task_types",
    "n_project_timeline_option_os_project_timeline": "project_timeline", "N_Project Timeline": "project_timeline",
  },
  BubbleStaffKPI: {
    "_id": "bubble_id",
    "score_number": "score", "Score": "score",
    "asana_link_text": "asana_link", "Asana Link": "asana_link",
    "kpi_sales_number": "kpi_sales", "KPI Sales": "kpi_sales",
    "related_file_file": "related_file_url", "Related File": "related_file_url",
    "self_point_number": "self_score", "Self Point": "self_score",
    "leader_comment_text": "leader_comment", "Leader Comment": "leader_comment",
    "working_folder_text": "box_folder", "Working Folder": "box_folder",
    "key_achievement_text": "key_achievement", "Key Achievement": "key_achievement",
    "project_custom_project": "project_id", "Project": "project_id",
    "improve_description_text": "improve_description", "Improve Description": "improve_description",
    "leader_suggest_point_number": "leader_suggest_score", "Leader Suggest Point": "leader_suggest_score",
    "breakthrough_description_text": "breakthrough_description", "Breakthrough Description": "breakthrough_description",
    "staff_kpi_month_custom_staff_kpi_month": "staff_kpi_month_id", "Staff KPI Month": "staff_kpi_month_id",
  },
  BubbleStaffKPIMonth: {
    "_id": "bubble_id",
    "report_month_date": "report_month", "Report Month": "report_month",
    "staff_custom_staff": "staff_id", "Staff": "staff_id",
    "company_comment_text": "company_comment", "Company Comment": "company_comment",
    "company_point_number": "company_point", "Company Point": "company_point",
  },
};

// Get all possible DB fields for a given entity (unique values from the map)
export function getEntityDbFields(entityName) {
  const map = IMPORT_FIELD_MAPS[entityName] || {};
  return [...new Set(Object.values(map))].sort();
}