// Shared menu structure for TopNavBar + Sidebar
export const HOME_ITEM = { label: "🏠 主頁", path: "/" };

export const menuGroups = [
  {
    key: "company",
    label: "公司資訊",
    icon: "🏢",
    color: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-400",
    gradient: "from-blue-500 to-cyan-500",
    items: [
      { label: "📰 公司新知", path: "/company/news" },
      { label: "📅 公司日曆", path: "/company/calendar" },
      { label: "📂 表格下載", path: "/company/forms" },
      { label: "📞 聯絡同事", path: "/company/contact" },
      { label: "❓ 公司FAQ", path: "/company/faq" },
      { label: "📦 物資借用", path: "/company/resources" },
      { label: "💰 P9費用報銷", path: "/company/expense" },
      { label: "🛎️ 行政協助", path: "/company/admin-help" },
    ],
  },
  {
    key: "app",
    label: "App資訊",
    icon: "📱",
    color: "text-purple-600",
    bg: "bg-purple-50",
    border: "border-purple-400",
    gradient: "from-purple-500 to-pink-500",
    items: [
      { label: "🔬 科技新聞", path: "/app/tech-news" },
      { label: "🛒 App Store", path: "/app/store" },
      { label: "💡 建議購買", path: "/app/suggest" },
    ],
  },
  {
    key: "work",
    label: "工作匯報",
    icon: "📊",
    color: "text-green-600",
    bg: "bg-green-50",
    border: "border-green-400",
    gradient: "from-green-500 to-emerald-500",
    items: [
      { label: "📝 每日工作匯報", path: "/work/daily" },
      { label: "📚 每星期學習匯報", path: "/work/weekly" },
      { label: "🎯 每月KPI匯報", path: "/work/kpi" },
      { label: "🚀 主要項目", path: "/work/projects" },
      { label: "✅ 特別批核", path: "/work/special-approval" },
      { label: "📋 年度工作評估", path: "/work/annual-review" },
    ],
  },
  {
    key: "attendance",
    label: "考勤假期",
    icon: "⏰",
    color: "text-orange-600",
    bg: "bg-orange-50",
    border: "border-orange-400",
    gradient: "from-orange-500 to-amber-500",
    items: [
      { label: "📋 簽到記錄", path: "/attendance/records" },
      { label: "👆 簽到打卡", path: "/attendance/checkin" },
      { label: "🌴 假期申請", path: "/attendance/leave" },
      { label: "⚡ 活動加班", path: "/attendance/overtime" },
    ],
  },
  {
    key: "course",
    label: "課程管理",
    icon: "🎓",
    color: "text-teal-600",
    bg: "bg-teal-50",
    border: "border-teal-400",
    gradient: "from-teal-500 to-cyan-500",
    items: [
      { label: "🏫 課程中心", path: "/course/center" },
      { label: "🗓️ 培訓日程", path: "/course/schedule" },
      { label: "📝 每星期匯報", path: "/course/weekly" },
      { label: "🧠 我的知識", path: "/course/my-knowledge" },
      { label: "📚 考試中心", path: "/course/exam" },
    ],
  },
  {
    key: "business",
    label: "業務拓展",
    icon: "💼",
    color: "text-pink-600",
    bg: "bg-pink-50",
    border: "border-pink-400",
    gradient: "from-pink-500 to-rose-500",
    items: [
      { label: "📋 Tender登記", path: "/business/tender" },
    ],
  },
  {
    key: "leader",
    label: "領袖管理",
    icon: "👑",
    color: "text-yellow-600",
    bg: "bg-yellow-50",
    border: "border-yellow-400",
    gradient: "from-yellow-500 to-orange-500",
    items: [
      { label: "👥 團隊管理", path: "/leader/team" },
      { label: "🎯 安排培訓", path: "/leader/training" },
      { label: "🏅 知識認證", path: "/leader/certification" },
    ],
  },
  {
    key: "adminfollow",
    label: "行政跟進",
    icon: "⚙️",
    color: "text-red-600",
    bg: "bg-red-50",
    border: "border-red-400",
    gradient: "from-red-500 to-rose-500",
    items: [
      { label: "✅ 批核申請", path: "/admin/approvals" },
      { label: "🌴 假期審批", path: "/admin/leave-approvals" },
      { label: "📋 考核安排", path: "/admin/assessment-arrangement" },
      { label: "📊 考核成績登記", path: "/admin/assessment-results" },
      { label: "👤 員工目錄", path: "/admin/staff" },
      { label: "🏗️ 組織架構設定", path: "/admin/org-settings" },
      { label: "🌏 地區管理", path: "/admin/regions" },
      { label: "🎉 新同事入職", path: "/admin/onboarding" },
      { label: "👋 同事離職", path: "/admin/offboarding" },
      { label: "📱 電話管理", path: "/admin/phones" },
      { label: "📊 功過記錄", path: "/admin/performance-records" },
      { label: "📲 App管理", path: "/admin/app-management" },
      { label: "🎓 課程管理", path: "/admin/course-management" },
    ],
  },
  {
    key: "superadmin",
    label: "管理員",
    icon: "👨‍💼",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-400",
    gradient: "from-indigo-500 to-purple-500",
    items: [
      { label: "📈 分析報表", path: "/superadmin/analytics" },
      { label: "📊 工作匯報報告", path: "/admin/manhour-report" },
      { label: "📈 績效總覽報告", path: "/admin/performance-report" },
      { label: "📋 年度評估表", path: "/admin/annual-reviews" },
      { label: "👥 同事互評管理", path: "/admin/peer-reviews" },
      { label: "📄 員工年度表現報告", path: "/admin/appraisal-reports" },
    ],
  },
];

export function findGroupByPath(pathname) {
  return menuGroups.find(g => g.items.some(it => it.path === pathname));
}